__title__ = 'SIGMOID'
__package_name__ = 'sigmoid'
__version__ = '0.0.1.10'
__description__ = "Sigmoid: Scalable Infrastructure for General Model Optimization on In-homogeneous Datasets"
__email__ = "community@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/sigmoid'
__pypi__ = 'https://pypi.org/project/sigmoid'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
